version: '3.8'
services:
  backend:
    build: ./Backend
    container_name: bazaarhub_backend
    ports:
      - "80:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bazaarhubdb
      - JWT_SECRET=YOUR_VERY_STRONG_JWT_SECRET_KEY
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./OMP
    container_name: bazaarhub_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: bazaarhub_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: